# Generated by Django 3.2.4 on 2022-05-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('arcgis_link', models.TextField()),
                ('jurisdiction_type', models.CharField(max_length=10)),
                ('jurisdiction_name', models.TextField()),
                ('data_type', models.CharField(max_length=20)),
                ('data_details', models.CharField(max_length=100)),
            ],
        ),
    ]
