# Generated by Django 3.2.4 on 2022-02-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Explore',
        ),
    ]
